image: python:2.7-stretch

before_script:
  # For testing, we need to build a fresh binary of GnuCash with Python bindings support straight
  # from the last stable release of GnuCash
  - apt-get update -qy
  - apt-get install -y python-pip git automake intltool libtool swig xsltproc libglib2.0-dev libgtk2.0-dev guile-2.0-dev libgnomecanvas2-dev libart-2.0-dev libgoffice-0.8-dev libgoffice-0.8-8 libxml2-dev libxslt1-dev libwebkitgtk-dev  libboost-all-dev libofx-dev python-dev libisocodes-dev
  - git clone https://github.com/Gnucash/gnucash.git
  # Enter into gnucash git repository and go to the last stable release
  - cd gnucash
  - lastrelease=$(git describe --tags `git rev-list --tags --max-count=1`) && echo $lastrelease
  - git checkout $lastrelease
  - ./autogen.sh
  - mkdir build && cd build
  - ../configure --prefix=/usr/local --enable-debug --enable-compile-warnings --enable-python --enable-ofx --disable-dbi
  - make && make install
  # Install the requirements for testing the project
  - pip install -r ../requirements.txt

test:
  script:
    - nosetests --with-coverage --cover-inclusive --cover-package=.
